spring:
  application:
    name: video
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  servlet:
    context-path: /api
data:
  temp-folder: /media/temp
minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  endpoint: ${MINIO_ENDPOINT}

bucket:
  name: video



