spring:
  application:
    name: test-data-keeper
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  scheduling:
    enabled: false
server:
  servlet:
    context-path: /api
  port: ${PORT:8090}
data:
  temp-folder: ${TEMP_FOLDER:temp}
storage:
  url: ${STORAGE_URL}
bucket:
  name: ${BUCKET_NAME}
  temp: ${BUCKET_TEMP_NAME}
prefix:
  dir: ${DIR_PREFIX}
url-lifetime: ${LIFETIME:3}
minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
key:
  access: ${ACCESS_SECRET}
  refresh: ${REFRESH_SECRET}
scheduler:
  interval: ${SECOND_INTERVAL:4}



