spring:
  application:
    name: video
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  servlet:
    context-path: /api
  port: 8200
data:
  temp-folder: /media/temp
minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  endpoint: ${MINIO_ENDPOINT}

bucket:
  name: ${BUCKET_NAME}
prefix:
  dir: ${DIR_PREFIX}
  public: ${PREFIX_PUBLIC}
  private: ${PREFIX_PRIVATE}
lifetime:
  url: ${LIFETIME_URL:3}




