spring:
  application:
    name: data-keeper
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: jdbc:mysql://${DB}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
server:
  servlet:
    context-path: /api
  port: ${PORT:8080}
data:
  temp-folder: ${TEMP_FOLDER:temp}
storage:
  url: ${STORAGE_URL}
bucket:
  name: ${BUCKET_NAME}
prefix:
  dir: ${DIR_PREFIX}
url-lifetime: ${LIFETIME:3}
minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
key:
  access: ${ACCESS_SECRET}
  refresh: ${REFRESH_SECRET}





