spring:
  application:
    name: video
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  servlet:
    context-path: /api
  port: ${PORT:8080}
data:
  temp-folder: ${TEMP_FOLDER:/media/temp}
storage:
  url: ${STORAGE_URL}
bucket:
  name: ${BUCKET_NAME}
prefix:
  dir: ${DIR_PREFIX}
  public: ${PREFIX_PUBLIC}
  private: ${PREFIX_PRIVATE}
lifetime:
  url: ${LIFETIME_URL:3}
minio:
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}




